package javatraining.oletsky.generics;

/**
 * @author O.Oletsky
 * A basic example of own generics
 * Of course, most of code was generated by the wizard
 */

public class DemoGenerics {
    public static void main(String[] args) {
        Gener<String> ekz1 = new Gener<>("qwerty");
        System.out.println(ekz1.getField());
        Gener<Integer> ekz2 = new Gener<>(10);
        System.out.println(ekz2.getField());
    }
}

class Gener<T> {
    private T field;

    public Gener(T field) {
        this.field = field;
    }

    public T getField() {
        return field;
    }

    public void setField(T field) {
        this.field = field;
    }
}
